// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn263Fv8BArWnh393KxIceAt9xlUWkRUI',
    appId: '1:570655000671:web:7ea390d54fb807d114f3ea',
    messagingSenderId: '570655000671',
    projectId: 'collegeapp-1',
    authDomain: 'collegeapp-1.firebaseapp.com',
    storageBucket: 'collegeapp-1.firebasestorage.app',
    measurementId: 'G-KGNRKBQVTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnFlacOCaiA9WpsE2XPs9irdSNoXX9z_U',
    appId: '1:570655000671:android:9049eda8397178a114f3ea',
    messagingSenderId: '570655000671',
    projectId: 'collegeapp-1',
    storageBucket: 'collegeapp-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqtDIURQsfPUpGgRzc5mFymedtvnA1tbg',
    appId: '1:570655000671:ios:57b7cd1ab235dab714f3ea',
    messagingSenderId: '570655000671',
    projectId: 'collegeapp-1',
    storageBucket: 'collegeapp-1.firebasestorage.app',
    iosBundleId: 'com.example.universityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqtDIURQsfPUpGgRzc5mFymedtvnA1tbg',
    appId: '1:570655000671:ios:57b7cd1ab235dab714f3ea',
    messagingSenderId: '570655000671',
    projectId: 'collegeapp-1',
    storageBucket: 'collegeapp-1.firebasestorage.app',
    iosBundleId: 'com.example.universityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn263Fv8BArWnh393KxIceAt9xlUWkRUI',
    appId: '1:570655000671:web:6340c640b34fd13414f3ea',
    messagingSenderId: '570655000671',
    projectId: 'collegeapp-1',
    authDomain: 'collegeapp-1.firebaseapp.com',
    storageBucket: 'collegeapp-1.firebasestorage.app',
    measurementId: 'G-8S1FVZ13M8',
  );
}
